### ISSUE TITLE
GETTING OVERFLOW ERROR

### ISSUE THREAD

**Issue by manirana1999** [Pure-L0G1C/Instagram#102]
PS C:\Users\acer\Desktop\Instagram-master> python instagram.py str1ker wrd.txt -m 0 -nc
Traceback (most recent call last):
  File "instagram.py", line 132, in <module>
    Engine(username, modes[mode], passlist, is_color).start()
  File "instagram.py", line 52, in start
    self.create_bruter()
  File "instagram.py", line 35, in create_bruter
    self.passlist_path
  File "C:\Users\acer\Desktop\Instagram-master\lib\bruter.py", line 29, in __init__
    passlist_path, threads)
  File "C:\Users\acer\Desktop\Instagram-master\lib\password_manager.py", line 25, in __init__
    Display.total_lines = self.count_lines()
  File "C:\Users\acer\Desktop\Instagram-master\lib\password_manager.py", line 50, in count_lines
    data = f.read(buffer)
OverflowError: cannot fit 'int' into an index-sized integer

**Comment by javadgh74** [comment]
i have this issue
please help

**Comment by Pure-L0G1C** [comment]
Sorry about that guys.

**Comment by Pure-L0G1C** [comment]
I made a few changes; can you guys check if the error still occurs?

**Comment by javadgh74** [comment]
I have this error: 

Traceback (most recent call last):
  File "instagram.py", line 132, in <module>
    Engine(username, modes[mode], passlist, is_color).start()
  File "instagram.py", line 52, in start
    self.create_bruter()
  File "instagram.py", line 35, in create_bruter
    self.passlist_path
  File "/home/javadkhan/Downloads/Instagram/lib/bruter.py", line 29, in __init__
    passlist_path, threads, self.display)
  File "/home/javadkhan/Downloads/Instagram/lib/password_manager.py", line 26, in __init__
    Display.total_lines = self.count_lines()
  File "/home/javadkhan/Downloads/Instagram/lib/password_manager.py", line 51, in count_lines
    with open(self.passlist_path, 'rb', buffering=(2 << 29)) as f:
MemoryError

**Comment by Pure-L0G1C** [comment]
I just fixed it. Sorry about that.

**Comment by javadgh74** [comment]
TNX Bro
