### ISSUE TITLE
model not found

### ISSUE THREAD

**Issue by sirdash** [Pure-L0G1C/Instagram#104]
hi
whent type  python3 instagram.py

i see error about colorama

Traceback (most recent call last):
  File "instagram.py", line 7, in <module>
    from lib.bruter import Bruter
  File "/home/sirdash/Instagram/lib/bruter.py", line 7, in <module>
    from lib.display import Display
  File "/home/sirdash/Instagram/lib/display.py", line 8, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

**Comment by Pure-L0G1C** [comment]
This is been resolved in version 3.0 https://youtube.com/watch?v=l6B9BaslDS8

**Comment by taghaviali34** [comment]
because i cant found the video pls give me the an other link thanks
