### ISSUE TITLE
proxi

### ISSUE THREAD

**Issue by Mananahmadi** [Pure-L0G1C/Instagram#105]
[i] Searching for proxies ...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "lib\password_manager.py", line 105, in start
  File "lib\password_manager.py", line 67, in read
  File "c:\users\mohamed\appdata\local\programs\python\python37\lib\codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 87: invalid start byte

**Comment by Pure-L0G1C** [comment]
I don’t maintain this codebase anymore
