### ISSUE TITLE
PROXIES error

### ISSUE THREAD

**Issue by Migateak** [Pure-L0G1C/Instagram#112]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Desktop\instaforce\lib\password_manager.py", line 105, in start      
    self.read()
  File "C:\Users\Desktop\instaforce\lib\password_manager.py", line 67, in read        
    for password in passlist:
  File "D:\Python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 52: invalid continuation byte

Uh help me please
thanks <3

**Comment by Migateak** [comment]
no it's okay, it's Just problem with caractere in my voca
