### ISSUE TITLE
stuck on installation

### ISSUE THREAD

**Issue by whosfry** [Pure-L0G1C/Instagram#113]
```
ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-gh1rl25c/instagram.py/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-gh1rl25c/instagram.py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/tmp/pip-install-gh1rl25c/instagram.py/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-gh1rl25c/instagram.py/setup.py", line 13, in <module>
        from InstagramPy import __version__
      File "/private/tmp/pip-install-gh1rl25c/instagram.py/InstagramPy/__init__.py", line 11, in <module>
        from .InstagramPySession import InstagramPySession, DEFAULT_PATH
      File "/private/tmp/pip-install-gh1rl25c/instagram.py/InstagramPy/InstagramPySession.py", line 12, in <module>
        from stem import Signal
    ModuleNotFoundError: No module named 'stem'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Pure-L0G1C** [comment]
That’s not my code

**Comment by whosfry** [comment]
I'm using mac i used 
`sudo pip3 install -U instagram.py`
is there something wrong?

**Comment by whosfry** [comment]
Hi! I fixed that many thanks" But now i get 
`[!] Invalid path to password list
`

**Comment by whosfry** [comment]
Sorry for so many questions!
Do I need to install tor or the proxies will do the same thing? Also the proxies work automatically or do i have to make any changes?
Thank you again!

**Comment by Pure-L0G1C** [comment]
That is not one of my code
