### ISSUE TITLE
No module named 'colorama'

### ISSUE THREAD

**Issue by adhiraj-ranjan** [Pure-L0G1C/Instagram#115]
In command line write:
$python3 instagram.py adhiraj_ranjan /storage/emulated/0/Android/old.txt -m 0

result:
Traceback (most recent call last):
File "instagram.py", line 7, in 
from lib.bruter import Bruter
File "/data/data/com.termux/files/home/Instagram/lib/bruter.py", line 7, in 
from lib.display import Display
File "/data/data/com.termux/files/home/Instagram/lib/display.py", line 8, in 
from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

(Even after install requirements.txt and again colorama manually...)

**Comment by zankoatzanko** [comment]
I had the same problem. And that's how it was resolved.
Try pip3 install colorama first If the problem doesn't work out, you can try the following options:
1.   redo everything from scratch
2.   update to the latest python.
