### ISSUE TITLE
Hello. I

### ISSUE THREAD

**Issue by SioVerino** [Pure-L0G1C/Instagram#116]
python instagram.py Traceback (most recent call last):   File "instagram.py", line 7, in <module>     from lib.bruter import Bruter   File "C:\Users\Siover\Desktop\Instagram\lib\bruter.py", line 7, in <module>     from lib.display import Display   File "C:\Users\Siover\Desktop\Instagram\lib\display.py", line 74
    f'[-] Wordlist: {self.passlist}\n[-] Username: {self.username}\n[-] Password: {password}')
                             ^ SyntaxError: invalid syntax

**Comment by vg0x01** [comment]
Use Python 3.6.
