### ISSUE TITLE
resume the attack 

### ISSUE THREAD

**Issue by Knrd2** [Pure-L0G1C/Instagram#135]
Hi, i want to resume the attack bc my laptop shutdown and now its searching for proxies the whole time and nothing happens... I let it run for about 2 days and now its stuck :/ 

Any help ?

**Comment by Knrd2** [comment]
Now im getting this error: 
[i] Searching for proxies ...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Instagram/lib/password_manager.py", line 105, in start
    self.read()
  File "/Users/Instagram/lib/password_manager.py", line 67, in read
    for password in passlist:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 7120: invalid continuation byte
