### ISSUE TITLE
No module named requests 

### ISSUE THREAD

**Issue by boss150** [Pure-L0G1C/Instagram#142]
I have installed requests but it showing this ''Traceback (most recent call last):
  File "instagram.py", line 7, in <module>
    from lib.bruter import Bruter
  File "/data/data/com.termux/files/home/Instagram/lib/bruter.py", line 6, in <module>
    from lib.browser import Browser
  File "/data/data/com.termux/files/home/Instagram/lib/browser.py", line 6, in <module>
    from requests import Session
ModuleNotFoundError: No module named 'requests''''

**Comment by Amank1647** [comment]
Use
pip3 install requests
(use pip/pip3 as per your version of pip)

**Comment by yasir999** [comment]
> Use
> pip3 install requests
> (use pip/pip3 as per your version of pip)

can u explain me in detail, what i need to do
