### ISSUE TITLE
Traceback (most recent call last):   File "instagram.py", line 7, in <module>     from lib.bruter import Bruter ModuleNotFoundError: No module named 'lib'

### ISSUE THREAD

**Issue by REDOXRAJ** [Pure-L0G1C/Instagram#150]
Traceback (most recent call last):
  File "instagram.py", line 7, in <module>
    from lib.bruter import Bruter
ModuleNotFoundError: No module named 'lib'
 
please help me how to fix it cause i want to hack my gf account cause i think she is cheatong on me

**Comment by amirrezagh75** [comment]
dude U have to use python 3.6 or newer version. First install python 3.6+.
 Then use this command to download the requirements:
``` python3.6  -m pip install -r requirements.txt ```

after that use
``` python3.6 instagram.py <username> <wordlist> -m <mode>```

**Comment by amirrezagh75** [comment]
> Traceback (most recent call last):
> File "instagram.py", line 7, in
> from lib.bruter import Bruter
> ModuleNotFoundError: No module named 'lib'
> 
> please help me how to fix it cause i want to hack my gf account cause i think she is cheatong on me

dude U have to use python 3.6 or newer version. First install python 3.6+.
Then use this command to download the requirements:
python3.6 -m pip install -r requirements.txt

after that use
python3.6 instagram.py <username> <wordlist> -m <mode>
