### ISSUE TITLE
Giving errors while installing on UBUNTU 18.04 LTS.

### ISSUE THREAD

**Issue by GauravWalia19** [Pure-L0G1C/Instagram#33]
Error:
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
While using pip install -r requirements.txt

**Comment by GauravWalia19** [comment]
###### Its also giving error while executing the script on Ubuntu 18.04 lts:
**Traceback (most recent call last):
  File "instagram.py", line 8, in <module>
    from lib.bruter import Bruter 
  File "/home/anonymous/Documents/Ethical Hacking/Instagram/lib/bruter.py", line 6, in <module>
    from .spyder import Spyder 
  File "/home/anonymous/Documents/Ethical Hacking/Instagram/lib/spyder.py", line 5, in <module>
    from .src.atom import Atom 
  File "/home/anonymous/Documents/Ethical Hacking/Instagram/lib/src/atom.py", line 5, in <module>
    from lib.wrap import Wrapper
ModuleNotFoundError: No module named 'lib.wrap'**

**Comment by Pure-L0G1C** [comment]
I'll fix it

**Comment by GauravWalia19** [comment]
Cool

**Comment by karthirama** [comment]
ERROR:
Traceback (most recent call last):
  File "instagram.py", line 6, in <module>
    from lib.bruter import Bruter
  File "/home/rama/Downloads/Instagram-master/lib/bruter.py", line 8, in <module>
    from .display import Display
  File "/home/rama/Downloads/Instagram-master/lib/display.py", line 8, in <module>
    from colorama import Fore 
ImportError: No module named colorama
