### ISSUE TITLE
Bug Report on win10

### ISSUE THREAD

**Issue by HuhMe9** [Pure-L0G1C/Instagram#34]
when i write python instgram.py i'v got this error code

C:\Users\HP\Desktop\المتطلبات\Instagram-master>python instagram.py Sami09.1 pass.lst 16
Traceback (most recent call last):
  File "instagram.py", line 8, in <module>
    from lib.bruter import Bruter
  File "C:\Users\HP\Desktop\المتطلبات\Instagram-master\lib\bruter.py", line 6, in <module>
    from .spyder import Spyder
  File "C:\Users\HP\Desktop\المتطلبات\Instagram-master\lib\spyder.py", line 5, in <module>
    from .src.atom import Atom
  File "C:\Users\HP\Desktop\المتطلبات\Instagram-master\lib\src\atom.py", line 5, in <module>
    from lib.wrap import Wrapper
ModuleNotFoundError: No module named 'lib.wrap'

please help me.
4 conact 

evilworld015@gmail.com

**Comment by Pure-L0G1C** [comment]
I'll work on it

**Comment by HuhMe9** [comment]
script is work now thx..
