### ISSUE TITLE
No module named request

### ISSUE THREAD

**Issue by Land0n271** [Pure-L0G1C/Instagram#65]
$ python instagram.py Sami09.1 dictionary.txt -m 0
Traceback (most recent call last):
File "instagram.py", line 6, in
from lib.bruter import Bruter
File "C:\Users\lan\Instagram-master\lib\bruter.py", line 6, in
from .browser import Browser
File "C:\Users\lan\Instagram-master\lib\browser.py", line 6, in
from requests import Session
ImportError: No module named requests

**Comment by Pure-L0G1C** [comment]
run the following code: ```pip install bs4 future requests colorama```
