### ISSUE TITLE
fails to launch

### ISSUE THREAD

**Issue by sshkrv** [Pure-L0G1C/Instagram#78]
[i] Searching for proxies ...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sabir/Instagram-master/lib/password_manager.py", line 89, in start
    self.read()
  File "/home/sabir/Instagram-master/lib/password_manager.py", line 51, in read
    Display.total_lines = self.count_lines()
  File "/home/sabir/Instagram-master/lib/password_manager.py", line 41, in count_lines
    chunk = f.raw.read(buffer)
AttributeError: 'file' object has no attribute 'raw'

**Comment by Pure-L0G1C** [comment]
I'll fix it

**Comment by Pure-L0G1C** [comment]
I fixed it

**Comment by sshkrv** [comment]
thanks! appreciate it
