### ISSUE TITLE
Error Message using RockYou.lst

### ISSUE THREAD

**Issue by ThomasWinn** [Pure-L0G1C/Instagram#81]
Traceback (most recent call last):
  File "instagram.py", line 123, in <module>
    Engine(username, modes[mode], passlist, is_color).start()
  File "instagram.py", line 67, in start
    self.bruter.start()
  File "/home/thomaswinn/Instagram/lib/bruter.py", line 170, in start
    browser.password, self.password_manager.attempts, len(self.browsers))
  File "/home/thomaswinn/Instagram/lib/display.py", line 54, in stats
    Fore.YELLOW, Fore.WHITE, Fore.CYAN, password, Fore.RESET
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 4: ordinal not in range(128)
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/bruter.py", line 82, in browser_manager
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116680 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116679 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116678 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116706 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116707 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116813 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116817 (most likely raised during interpreter shutdown):Exception in thread Thread-116641 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116708 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116811 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116709 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116597 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116677 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/password_manager.py", line 93, in start
  File "/home/thomaswinn/Instagram/lib/password_manager.py", line 74, in read
  File "/home/thomaswinn/Instagram/lib/password_manager.py", line 27, in list_size
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116607 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116814 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116704 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116705 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/thomaswinn/Instagram/lib/browser.py", line 117, in attempt
  File "/home/thomaswinn/Instagram/lib/browser.py", line 120, in close
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 708, in close
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-116810 (most likely raised during interpreter shutdown):Exception in thread Thread-116815 (most likely raised during interpreter shutdown):Exception in thread Thread-116812 (most likely raised during interpreter shutdown)

**Comment by Pure-L0G1C** [comment]
Use Python 3
