### ISSUE TITLE
Why does this happen when I try to use it?

### ISSUE THREAD

**Issue by njrdgn** [Pure-L0G1C/Instagram#83]
Traceback (most recent call last):
  File "instagram.py", line 7, in <module>
    from lib.bruter import Bruter
  File "/root/Instagram/lib/bruter.py", line 6, in <module>
    from .browser import Browser
  File "/root/Instagram/lib/browser.py", line 7, in <module>
    from requests import Session
ModuleNotFoundError: No module named 'requests'

**Comment by Pure-L0G1C** [comment]
You need to run: python3 install.py

**Comment by njrdgn** [comment]
I've definitely done that
