### ISSUE TITLE
python instagram.py issue

### ISSUE THREAD

**Issue by buddhachuong** [Pure-L0G1C/Instagram#84]
root@kali:~/Desktop/Instagram# cd Desktop
bash: cd: Desktop: No such file or directory
root@kali:~/Desktop/Instagram# cd
root@kali:~# ls
Desktop    Downloads      Music     Public     Videos
Documents  file_to_crack  Pictures  Templates
root@kali:~# cd 
root@kali:~# Desktop
bash: Desktop: command not found
root@kali:~# cd Desktop
root@kali:~/Desktop# ls
Instagram
root@kali:~/Desktop# ls
Instagram  Instagram-master.zip
root@kali:~/Desktop# cd desktop
bash: cd: desktop: No such file or directory
root@kali:~/Desktop# ls
Instagram
root@kali:~/Desktop# cd Instagram
root@kali:~/Desktop/Instagram# ls
diff.py     Instagram-master.zip  LICENSE    requirements.txt
Executable  instagram.py          READ.md    test_proxies.py
hama.txt    lib                   README.md
root@kali:~/Desktop/Instagram# nano.readme
bash: nano.readme: command not found
root@kali:~/Desktop/Instagram# nano READ.md
root@kali:~/Desktop/Instagram# ^C
root@kali:~/Desktop/Instagram# chmod +x instagram.py
root@kali:~/Desktop/Instagram# python instgram.py
python: can't open file 'instgram.py': [Errno 2] No such file or directory
root@kali:~/Desktop/Instagram# python3 instgram.py
python3: can't open file 'instgram.py': [Errno 2] No such file or directory
root@kali:~/Desktop/Instagram# python 3 instgram.py
python: can't open file '3': [Errno 2] No such file or directory

So i keep coming to this issue the instagram.py cant be opened? 
Thanks for your time!

**Comment by xianrusso** [comment]
Hey!  You spelled "instagram.py" wrong for the last two entries, as well as spelling "python3" wrong, which is why the compiler can't locate the "3" file.

**Comment by jasmineramona** [comment]
I specialise in Instagram hacking. Contact me if you need paid help. (jasmineramona@protonmail.com)

**Comment by Ulafala** [comment]
root@kali:~/Desktop/Instagram# python instagram.py
Traceback (most recent call last):
  File "instagram.py", line 7, in <module>
    from lib.bruter import Bruter
  File "/root/Desktop/Instagram/lib/bruter.py", line 8, in <module>
    from .display import Display
  File "/root/Desktop/Instagram/lib/display.py", line 74
    f'[-] Wordlist: {self.passlist}\n[-] Username: {self.username}\n[-] Password: {password}')
                                                                                            ^
SyntaxError: invalid syntax

Help me pls

**Comment by Pure-L0G1C** [comment]
I’m no longer maintaining this repo

**Comment by mcgregol** [comment]
@Ulafala I'm having the same problem as well.  I have looked around but no one else besides you and me have encountered it.  With the owner no longer working on it I think I will just use something else.

**Comment by Ulafala** [comment]
@mcgregol I've got the solution

**Comment by mcgregol** [comment]
@Ulafala What was the problem?

**Comment by Fardeen-khan** [comment]
> root@kali:~/Desktop/Instagram# python instagram.py
> Traceback (most recent call last):
> File "instagram.py", line 7, in
> from lib.bruter import Bruter
> File "/root/Desktop/Instagram/lib/bruter.py", line 8, in
> from .display import Display
> File "/root/Desktop/Instagram/lib/display.py", line 74
> f'[-] Wordlist: {self.passlist}\n[-] Username: {self.username}\n[-] Password: {password}')
> ^
> SyntaxError: invalid syntax
> 
> Help me pls

try using python3 at the beginning instead of python

**Comment by SioVerino** [comment]
> @Ulafala What was the problem?

You have  to install module requests
