### ISSUE TITLE
Encoding problem in Windows

### ISSUE THREAD

**Issue by keomd** [Pure-L0G1C/Instagram#89]
env :  Windows 7 + git-bash
I get the following Error while hitting following command:
`python instagram.py USER PASS.text -m 0`

`Traceback (most recent call last):                                                                                                              File "instagram.py", line 130, in                                                                                                       Engine(username, modes[mode], passlist, is_color).start()                                                                                   File "instagram.py", line 69, in start                                                                                                          self.bruter.start()                                                                                                                         File "C:\Users\PC\PycharmProjects\Instagram22\lib\bruter.py", line 170, in start                                                                browser.password, self.password_manager.attempts, len(self.browsers))                                                                       File "C:\Users\PC\PycharmProjects\Instagram22\lib\display.py", line 53, in stats                                                                Fore.YELLOW, Fore.WHITE, Fore.CYAN, password, Fore.RESET                                                                                    File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\encodings\cp1256.py", line 19, in encode                                           return codecs.charmap_encode(input,self.errors,encoding_table)[0]                                                                         UnicodeEncodeError: 'charmap' codec can't encode character '\xaa' in position 40: character maps to  <undefined>`

**Comment by Pure-L0G1C** [comment]
Try using -nc option

**Comment by keomd** [comment]
the problem is Due to internet disconnection, I encounter it several times exactly when the internet is broken, I guess Error handling is required to manage the problem.
