### ISSUE TITLE
Can't run the script on Ubuntu 16.04

### ISSUE THREAD

**Issue by mehrunrasoli** [Pure-L0G1C/Instagram#90]
I tried to run this script on the Ubuntu 16.04 but after installing dependencies still, I get this error.

```bash
$ python3 --version
Python 3.5.2

$ pip3 --version
pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5) 

$ python3 instagram.py

Traceback (most recent call last):
  File "instagram.py", line 7, in <module>
    from lib.bruter import Bruter
  File "/home/mehrun/code/Instagram/lib/bruter.py", line 8, in <module>
    from .display import Display
  File "/home/mehrun/code/Instagram/lib/display.py", line 74
    f'[-] Wordlist: {self.passlist}\n[-] Username: {self.username}\n[-] Password: {password}')
                                                                                            ^
SyntaxError: invalid syntax
```

**Comment by Pure-L0G1C** [comment]
use Python 3.6 or later

**Comment by m-henderson** [comment]
@Pure-L0G1C can we create an issue to update the requirements in the readme?
