### ISSUE TITLE
Error Traceback (most recent call last)

### ISSUE THREAD

**Issue by hasandoulabi** [Pure-L0G1C/Instagram#95]
in command line write :

python3 instagram.py hasan__monfared requirements.txt  -m 0

result:
Traceback (most recent call last):
  File "instagram.py", line 7, in <module>
    from lib.bruter import Bruter
  File "/root/Desktop/lib/bruter.py", line 8, in <module>
    from .display import Display
  File "/root/Desktop/lib/display.py", line 74
    f'[-] Wordlist: {self.passlist}\n[-] Username: {self.username}\n[-] Password: {password}')
                                                                                            ^
SyntaxError: invalid syntax

**Comment by sidwise** [comment]
Run it on python 3-6

**Comment by adhiraj-ranjan** [comment]
python3 instagram.py adhiraj_ranjan /storage/emulated/0/Android/old.txt -m 0

result:
Traceback (most recent call last):
  File "instagram.py", line 7, in <module>
    from lib.bruter import Bruter
  File "/data/data/com.termux/files/home/Instagram/lib/bruter.py", line 7, in <module>
    from lib.display import Display
  File "/data/data/com.termux/files/home/Instagram/lib/display.py", line 8, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'
